language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

#git:
#    submodules: false

#before_install:
#    - git submodule update --init --recursive --remote --force
#    - git submodule foreach -q --recursive 'branch="$(git config -f $toplevel/.gitmodules submodule.$name.branch)"; git fetch --all; git checkout $branch; git pull'

before_script:
    - composer self-update
    - composer install

script:
    - ./build/tools/phpunit.phar --configuration ./build/travis-ci.xml

notifications:
  email: false
