language: php

sudo: false

php:
#    - 5.5
    - 5.6
    - 7.0
#    - 7.1
#    - hhvm

branches:
  only:
    - master
    - develop

env:
  - LARAVEL_VERSION="5.0.*" TESTBENCH_VERSION="3.0.*" PHPUNIT_VERSION="~4.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true
  - LARAVEL_VERSION="5.1.*" TESTBENCH_VERSION="3.1.*" PHPUNIT_VERSION="~4.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true
  - LARAVEL_VERSION="5.2.*" TESTBENCH_VERSION="3.2.*" PHPUNIT_VERSION="~4.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true
  - LARAVEL_VERSION="5.3.*" TESTBENCH_VERSION="3.3.*" PHPUNIT_VERSION="~5.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true
  - LARAVEL_VERSION="5.4.*" TESTBENCH_VERSION="3.4.*" PHPUNIT_VERSION="~5.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true

before_install:
  - if [[ $TRAVIS_PHP_VERSION == 7.0 && "${PHPUNIT_VERSION}" == "~4.0" ]] ; then exit 0;fi

install:
  - composer require laravel/framework:${LARAVEL_VERSION}
  - composer require orchestra/testbench:${TESTBENCH_VERSION}
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
    - phpunit -c phpunit.xml
    #- phpunit -c phpunit.xml --coverage-clover=coverage.clover

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover


