language: php

sudo: false

php:
  - 5.6
  - 7.0

env:
  - LARAVEL_VERSION="5.0.*" TESTBENCH_VERSION="3.0.*" PHPUNIT_VERSION="~4.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true
  - LARAVEL_VERSION="5.1.*" TESTBENCH_VERSION="3.1.*" PHPUNIT_VERSION="~4.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true
  - LARAVEL_VERSION="5.2.*" TESTBENCH_VERSION="3.2.*" PHPUNIT_VERSION="~4.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true
  - LARAVEL_VERSION="5.3.*" TESTBENCH_VERSION="3.3.*" PHPUNIT_VERSION="~5.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true
  - LARAVEL_VERSION="5.4.*" TESTBENCH_VERSION="3.4.*" PHPUNIT_VERSION="~5.0" BLADE_EXTENSIONS_MARKDOWN_ENABLED=true BLADE_EXTENSIONS_MARKDOWN_VIEWS=true BLADE_EXTENSIONS_EXAMPLE_VIEWS=true

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - if [[ $TRAVIS_PHP_VERSION == 7.0 && "${PHPUNIT_VERSION}" == "~4.0" ]] ; then exit 0;fi
  - travis_retry composer self-update

install:
  - composer install --prefer-source --no-interaction
  - composer require laravel/framework:${LARAVEL_VERSION}
  - composer require orchestra/testbench:${TESTBENCH_VERSION}
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}

script: vendor/bin/phpunit

after_success:
  - curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
  - chmod a+x /tmp/travis-automerge
  - BRANCHES_TO_MERGE_REGEX='^f/' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=robinradic/blade-extensions /tmp/travis-automerge
